[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.54"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo  --gc --minify --enableGitInfo"

[context.deploy-preview.environment]
HUGO_VERSION = "0.54"

