FileVersion = 1
Projects = {StubUI = {Path = "."}, Beefy2D = "*", SDL2 = "*"}
Unlocked = ["Beefy2D", "corlib", "SDL2"]

[Workspace]
StartupProject = "StubUI"

[Configs.Debug.Win64]
AllocType = "CRT"
IntermediateType = "ObjectAndIRCode"
