FileVersion = 1
Projects = {StubUI = {Path = "."}, Beefy2D = "*"}
Unlocked = ["Beefy2D", "corlib"]

[Workspace]
StartupProject = "StubUI"

[Configs.Debug.Win64]
AllocType = "CRT"
IntermediateType = "ObjectAndIRCode"

[Configs.Release.Win64]
Toolset = "Microsoft"
LTOType = "None"
