# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Documentation"
  url = "/docs"
  weight = 20

[[main]]
  name = "Doxygen"
  url = "/docs/doxygen/corlib/html/"
  weight = 20

[[main]]
  name = "Releases"
  url = "#releases"
  weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

