FileVersion = 1
Projects = {Stub = {Path = "."}, MiniZ = "*"}
Unlocked = ["MiniZ", "corlib"]

[Workspace]
StartupProject = "Stub"

[Configs.Debug.Win64]
AllocType = "CRT"
EnableObjectDebugFlags = false
IntermediateType = "ObjectAndIRCode"
