FileVersion = 1
Dependencies = {corlib = "*", SDL2 = "*"}

[Project]
Name = "SpaceGame"
TargetType = "BeefGUIApplication"
StartupObject = "SpaceGame.Program"

[Configs.Debug.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"
TargetName = "$(ProjectName)_d"

[Configs.Debug.Linux64]
TargetDirectory = "$(WorkspaceDir)/dist"
OtherLinkFlags = "$(LinkFlags) -lSDL2 -lSDL2_ttf -LSDL2_image -LSDL2_mixer"
CLibType = "Static"
BeefLibType = "Static"
LibPaths = ["sdl2.a"]

[Configs.Release.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"

[Configs.Release.Linux64]
TargetDirectory = "$(WorkspaceDir)/dist"
OtherLinkFlags = "$(LinkFlags) -lSDL2 -lSDL2_ttf -LSDL2_image -LSDL2_mixer"

[Configs.Paranoid.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"

[Configs.Paranoid.Linux64]
TargetDirectory = "$(WorkspaceDir)/dist"
OtherLinkFlags = "$(LinkFlags) -lSDL2 -lSDL2_ttf -LSDL2_image -LSDL2_mixer"
CLibType = "Static"
BeefLibType = "Static"

[Configs.Test.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"

[Configs.Test.Linux64]
BuildKind = "Normal"
TargetDirectory = "$(WorkspaceDir)/dist"
OtherLinkFlags = "$(LinkFlags) -lSDL2 -lSDL2_ttf -LSDL2_image -LSDL2_mixer"
CLibType = "Static"
BeefLibType = "Static"
