FileVersion = 1
Dependencies = {corlib = "*", SDL2 = "*"}

[Project]
Name = "SpaceGame"
TargetType = "BeefWindowsApplication"
StartupObject = "SpaceGame.Program"

[Configs.Debug.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"
TargetName = "$(ProjectName)_d"

[Configs.Release.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"

[Configs.Paranoid.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"

[Configs.Test.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"
