FileVersion = 1
Projects = {SpaceGame = {Path = "."}, SDL2 = {Path = "../BeefLibs/SDL2"}}

[Workspace]
StartupProject = "SpaceGame"

[Configs.Debug.Win64]
EnableRealtimeLeakCheck = false
IntermediateType = "ObjectAndIRCode"
